{{- if and .Values.global.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cdi-operator
  labels:
    {{- include "cdi.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi-operator-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "cdi.operator.serviceAccountName" . }}
    namespace: {{ include "cdi.namespace" . }}
{{- end }}
