{{- if and .Values.global.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cdi-operator
  namespace: {{ include "cdi.namespace" . }}
  labels:
    {{- include "cdi.operator.labels" . | nindent 4 }}
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-operator
    cdi.kubevirt.io: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cdi-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "cdi.operator.serviceAccountName" . }}
    namespace: {{ include "cdi.namespace" . }}
{{- end }}
