{{- if and .Values.global.enabled .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cdi.operator.serviceAccountName" . }}
  namespace: {{ include "cdi.namespace" . }}
  labels:
    operator.cdi.kubevirt.io: ""
{{- with .Values.operator.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
