apiVersion: v2
name: roundcube
description: A free and open source webmail solution with a desktop-like user interface
type: application
version: 0.2.3
appVersion: "1.6.11"
keywords:
  - roundcube
  - webmail
  - email
  - mail
home: https://github.com/encircle360-oss/helm-charts/tree/main/charts/roundcube
sources:
  - https://github.com/roundcube/roundcubemail
  - https://github.com/encircle360-oss/helm-charts
maintainers:
  - name: encircle360-oss
    email: oss@encircle360.com
icon: https://raw.githubusercontent.com/roundcube/roundcubemail/master/skins/elastic/images/logo.svg
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: added
      description: Multi-domain support with flexible per-domain configuration
    - kind: added
      description: Support for ManageSieve, LDAP and other advanced configurations per domain
    - kind: changed
      description: Improved configuration flexibility with generic config blocks
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
    - url: https://artifacthub.io/packages/helm/bitnami/mariadb
