apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roundcube.fullname" . }}
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
type: Opaque
data:
  des-key: {{ include "roundcube.desKey" . | b64enc | quote }}
---
{{- if and (ne .Values.database.type "sqlite") (not .Values.database.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roundcube.fullname" . }}-db
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.external.existingSecretUserKey }}: {{ .Values.database.external.user | b64enc | quote }}
  {{ .Values.database.external.existingSecretPasswordKey }}: {{ .Values.database.external.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.redis.enabled .Values.redis.password (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roundcube.fullname" . }}-redis
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.existingSecretPasswordKey }}: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.roundcube.pluginSecrets (not .Values.roundcube.pluginSecretsExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roundcube.fullname" . }}-plugin-secrets
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.roundcube.pluginSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
